# Generated by Django 5.1.2 on 2025-09-18 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0007_alter_userprofile_ahpra_registration_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('program_type', models.CharField(choices=[('5+1', '5+1 Internship Program'), ('4+2', '4+2 Internship Program'), ('CUSTOM', 'Custom Program')], max_length=10)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('total_hours_required', models.IntegerField(default=1500)),
                ('practice_hours_required', models.IntegerField(default=1360)),
                ('dcc_hours_minimum', models.IntegerField(default=500)),
                ('dcc_simulated_maximum', models.IntegerField(default=60)),
                ('supervision_hours_minimum', models.IntegerField(default=80)),
                ('pd_hours_required', models.IntegerField(default=60)),
                ('minimum_weeks', models.IntegerField(default=44)),
                ('minimum_weekly_hours', models.FloatField(default=17.5)),
                ('supervision_ratio', models.FloatField(default=17.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_completion_weeks', models.IntegerField(default=52)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('current_week', models.IntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('weekly_validation_passed', models.BooleanField(default=True)),
                ('category_validation_passed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_validation.internshipprogram')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internship_progress', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('WEEKLY_MINIMUM', 'Weekly Minimum Not Met'), ('CATEGORY_MINIMUM', 'Category Minimum Not Met'), ('SIMULATED_EXCEEDED', 'Simulated Hours Exceeded'), ('SUPERVISION_RATIO', 'Supervision Ratio Not Met'), ('COMPLETION_BLOCKED', 'Completion Blocked')], max_length=20)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('dcc_hours', models.FloatField(default=0)),
                ('dcc_simulated_hours', models.FloatField(default=0)),
                ('cra_hours', models.FloatField(default=0)),
                ('pd_hours', models.FloatField(default=0)),
                ('supervision_hours', models.FloatField(default=0)),
                ('meets_weekly_minimum', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'week_number')},
            },
        ),
    ]
