# Generated by Django 5.1.2 on 2025-09-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_validation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipprogram',
            name='program_type',
            field=models.CharField(choices=[('5+1', '5+1 Internship Program'), ('4+2', '4+2 Internship Program'), ('CUSTOM', 'Custom Program')], max_length=10, unique=True),
        ),
    ]
