# Generated by Django 5.1.2 on 2025-09-15 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_organization_reflection_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.organization'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('PROVISIONAL', 'Provisional Psychologist'), ('REGISTRAR', 'Psychology Registrar'), ('SUPERVISOR', 'Board-Approved Supervisor'), ('ORG_ADMIN', 'Organisation Admin')], default='PROVISIONAL', max_length=32),
        ),
    ]
