# Generated by Django 5.1.2 on 2025-09-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userprofile_ahpra_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aope',
            field=models.CharField(blank=True, choices=[('CLINICAL', 'Clinical Psychology'), ('FORENSIC', 'Forensic Psychology'), ('ORGANISATIONAL', 'Organisational Psychology'), ('SPORT_EXERCISE', 'Sport and Exercise Psychology'), ('COMMUNITY', 'Community Psychology'), ('COUNSELLING', 'Counselling Psychology'), ('EDUCATIONAL_DEVELOPMENTAL', 'Educational and Developmental Psychology'), ('HEALTH', 'Health Psychology'), ('NEUROPSYCHOLOGY', 'Neuropsychology')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='program_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qualification_level',
            field=models.CharField(blank=True, choices=[('MASTERS', 'Masters'), ('COMBINED', 'Combined Masters/PhD'), ('DOCTORATE', 'Doctorate'), ('SECOND_AOPE', 'Second AoPE')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_commitment',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
