# Generated by Django 5.1.2 on 2025-09-18 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_userprofile_city_userprofile_mobile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorEndorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endorsement', models.CharField(choices=[('CLINICAL', 'Clinical Psychology'), ('COUNSELLING', 'Counselling Psychology'), ('EDUCATIONAL', 'Educational Psychology'), ('FORENSIC', 'Forensic Psychology'), ('HEALTH', 'Health Psychology'), ('NEUROPSYCHOLOGY', 'Neuropsychology'), ('ORGANISATIONAL', 'Organisational Psychology'), ('SPORT', 'Sport Psychology'), ('COMMUNITY', 'Community Psychology')], max_length=50)),
                ('endorsement_date', models.DateField()),
                ('endorsement_body', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_endorsements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['supervisor', 'endorsement'],
                'unique_together': {('supervisor', 'endorsement')},
            },
        ),
    ]
