# Generated by Django 5.1.2 on 2025-09-19 04:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_supervision_redesign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supervision',
            name='unique_supervision_invitation',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='intern_start_date',
            new_name='provisional_start_date',
        ),
        migrations.AlterUniqueTogether(
            name='supervision',
            unique_together={('supervisor', 'supervisee_email', 'role')},
        ),
    ]
