# Generated by Django 5.1.2 on 2025-09-20 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_supervision_unique_supervision_invitation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorinvitation',
            name='message',
        ),
        migrations.RemoveField(
            model_name='supervisorrequest',
            name='message',
        ),
        migrations.RemoveField(
            model_name='supervisionnotification',
            name='supervision',
        ),
        migrations.AlterUniqueTogether(
            name='supervisorendorsement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='supervisorendorsement',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='supervisorinvitation',
            name='trainee',
        ),
        migrations.RemoveField(
            model_name='supervisorrequest',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='supervisorrequest',
            name='trainee',
        ),
        migrations.AlterModelOptions(
            name='supervision',
            options={},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='provisional_start_date',
            new_name='intern_start_date',
        ),
        migrations.AlterUniqueTogether(
            name='supervision',
            unique_together={('supervisor', 'supervisee')},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='aope',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='principal_supervisor_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='program_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='qualification_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='secondary_supervisor_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='target_weeks',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weekly_commitment',
        ),
        migrations.AddField(
            model_name='supervision',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='supervisee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='supervisors_links', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supervision',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisees_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ahpra_registration_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='supervisor_emails',
            field=models.TextField(blank=True, help_text='Supervisor email addresses, one per line'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='SupervisionNotification',
        ),
        migrations.DeleteModel(
            name='SupervisorEndorsement',
        ),
        migrations.DeleteModel(
            name='SupervisorInvitation',
        ),
        migrations.DeleteModel(
            name='SupervisorRequest',
        ),
        migrations.RemoveField(
            model_name='supervision',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='supervision',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supervision',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='supervision',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='supervision',
            name='role',
        ),
        migrations.RemoveField(
            model_name='supervision',
            name='status',
        ),
        migrations.RemoveField(
            model_name='supervision',
            name='supervisee_email',
        ),
        migrations.RemoveField(
            model_name='supervision',
            name='verification_token',
        ),
    ]
