# Generated by Django 5.1.2 on 2025-09-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_supervision_unique_supervision_invitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Whether the user has completed their profile setup'),
        ),
    ]
