# Generated by Django 5.1.2 on 2025-09-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_profile_completed_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_login_completed',
            field=models.BooleanField(default=False, help_text='Whether the user has completed their first login'),
        ),
    ]
