# Generated by Django 5.1.2 on 2025-09-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_first_login_completed_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='area_of_practice_endorsement',
            field=models.CharField(blank=True, help_text='Area of practice endorsement (Clinical, Forensic, Counselling, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_supervise_provisionals',
            field=models.BooleanField(default=False, help_text='Whether the supervisor can supervise provisional psychologists'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_supervise_registrars',
            field=models.BooleanField(default=False, help_text='Whether the supervisor can supervise psychology registrars'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='endorsement_start_date',
            field=models.DateField(blank=True, help_text='Date when endorsement was obtained', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='general_registration_year',
            field=models.IntegerField(blank=True, help_text='Year of general registration', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_board_approved_supervisor',
            field=models.BooleanField(default=False, help_text='Whether the user is a board-approved supervisor'),
        ),
    ]
