# Generated by Django 5.1.2 on 2025-09-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_endorsement_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='initials_url',
            field=models.TextField(blank=True, help_text='Initials image (data URL or path)'),
        ),
    ]
