# Generated by Django 5.1.2 on 2025-09-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_supervision_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prior_hours_declined',
            field=models.BooleanField(default=False, help_text='Whether the user declined to enter prior hours'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prior_hours_submitted',
            field=models.BooleanField(default=False, help_text='Whether prior hours have been submitted and locked'),
        ),
    ]
