# Generated by Django 5.1.2 on 2025-09-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_provisional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='weekly_commitment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weekly_commitment_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weekly commitment in hours', max_digits=5, null=True),
        ),
    ]
