# Generated by Django 5.1.2 on 2025-10-18 12:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_create_meeting_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('INVITE', 'Invite'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('UNLOCK', 'Unlock'), ('LOCK', 'Lock'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('OTHER', 'Other')], max_length=20)),
                ('resource_type', models.CharField(choices=[('USER_PROFILE', 'User Profile'), ('WEEKLY_LOGBOOK', 'Weekly Logbook'), ('SECTION_A_ENTRY', 'Section A Entry'), ('SECTION_B_ENTRY', 'Section B Entry'), ('SECTION_C_ENTRY', 'Section C Entry'), ('SUPERVISION', 'Supervision'), ('SUPERVISION_REQUEST', 'Supervision Request'), ('SUPERVISION_INVITATION', 'Supervision Invitation'), ('MEETING', 'Meeting'), ('MESSAGE', 'Message'), ('NOTIFICATION', 'Notification'), ('UNLOCK_REQUEST', 'Unlock Request'), ('REVIEW_REQUEST', 'Review Request'), ('AUDIT_LOG', 'Audit Log'), ('SYSTEM', 'System'), ('OTHER', 'Other')], max_length=30)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the affected resource', max_length=100, null=True)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('details', models.JSONField(default=dict, help_text='Additional context and data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisconnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary Supervisor'), ('SECONDARY', 'Secondary Supervisor')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message from supervisee to supervisor')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True, help_text='Optional notes from supervisor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('SUPERVISOR_REQUEST', 'Supervisor Request'), ('SUPERVISOR_RESPONSE', 'Supervisor Response'), ('SYSTEM_NOTIFICATION', 'System Notification'), ('GENERAL', 'General Message')], default='GENERAL', max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('ARCHIVED', 'Archived')], default='UNREAD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupervisionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('INVITE_SENT', 'Invite Sent'), ('REMINDER_SENT', 'Reminder Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('in_app_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorEndorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endorsement', models.CharField(choices=[('CLINICAL', 'Clinical Psychology'), ('FORENSIC', 'Forensic Psychology'), ('ORGANISATIONAL', 'Organisational Psychology'), ('SPORT_EXERCISE', 'Sport and Exercise Psychology'), ('COMMUNITY', 'Community Psychology'), ('COUNSELLING', 'Counselling Psychology'), ('EDUCATIONAL_DEVELOPMENTAL', 'Educational and Developmental Psychology'), ('HEALTH', 'Health Psychology'), ('NEUROPSYCHOLOGY', 'Neuropsychology')], max_length=50)),
                ('endorsement_date', models.DateField()),
                ('endorsement_body', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['supervisor', 'endorsement'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_email', models.EmailField(max_length=254)),
                ('supervisor_name', models.CharField(blank=True, max_length=255)),
                ('capacity', models.CharField(choices=[('PRINCIPAL', 'Principal Supervisor'), ('SECONDARY', 'Secondary Supervisor')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('invitation_token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(choices=[('PRINCIPAL', 'Principal Supervisor'), ('SECONDARY', 'Secondary Supervisor')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='supervision',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='intern_start_date',
            new_name='provisional_start_date',
        ),
        migrations.RenameIndex(
            model_name='meeting',
            new_name='api_meeting_organiz_4cfb1c_idx',
            old_name='api_meeting_organizer_start_time_idx',
        ),
        migrations.RenameIndex(
            model_name='meeting',
            new_name='api_meeting_start_t_f68e86_idx',
            old_name='api_meeting_start_end_time_idx',
        ),
        migrations.RenameIndex(
            model_name='meeting',
            new_name='api_meeting_status_0593aa_idx',
            old_name='api_meeting_status_idx',
        ),
        migrations.AlterUniqueTogether(
            name='supervision',
            unique_together={('supervisor', 'supervisee_email', 'role')},
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='registration_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='supervision',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervision',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervision',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervision',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervision',
            name='role',
            field=models.CharField(choices=[('PRIMARY', 'Primary Supervisor'), ('SECONDARY', 'Secondary Supervisor')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervision',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='supervision',
            name='supervisee_email',
            field=models.EmailField(default='Australia/Melbourne', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervision',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aope',
            field=models.CharField(blank=True, choices=[('CLINICAL', 'Clinical Psychology'), ('FORENSIC', 'Forensic Psychology'), ('ORGANISATIONAL', 'Organisational Psychology'), ('SPORT_EXERCISE', 'Sport and Exercise Psychology'), ('COMMUNITY', 'Community Psychology'), ('COUNSELLING', 'Counselling Psychology'), ('EDUCATIONAL_DEVELOPMENTAL', 'Educational and Developmental Psychology'), ('HEALTH', 'Health Psychology'), ('NEUROPSYCHOLOGY', 'Neuropsychology')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='principal_supervisor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='program_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qualification_level',
            field=models.CharField(blank=True, choices=[('MASTERS', 'Masters'), ('COMBINED', 'Combined Masters/PhD'), ('DOCTORATE', 'Doctorate'), ('SECOND_AOPE', 'Second AoPE')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondary_supervisor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_commitment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='supervisee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisions_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ahpra_registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='supervisor_emails',
            field=models.TextField(blank=True, help_text='Additional supervisor email addresses, one per line'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disconnectionrequest',
            name='supervisee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disconnection_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disconnectionrequest',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disconnection_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supervisionnotification',
            name='supervision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.supervision'),
        ),
        migrations.AddField(
            model_name='supervisorendorsement',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_endorsements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supervisorinvitation',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_invitation', to='api.message'),
        ),
        migrations.AddField(
            model_name='supervisorinvitation',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supervisorrequest',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_request', to='api.message'),
        ),
        migrations.AddField(
            model_name='supervisorrequest',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supervisorrequest',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='supervision',
            name='active',
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='api_auditlo_user_id_b608a1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='api_auditlo_action_e69819_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'created_at'], name='api_auditlo_resourc_bddbfc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['result', 'created_at'], name='api_auditlo_result_6c4eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', 'created_at'], name='api_auditlo_ip_addr_233ca2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='disconnectionrequest',
            unique_together={('supervisee', 'supervisor', 'role', 'status')},
        ),
        migrations.AlterUniqueTogether(
            name='supervisorendorsement',
            unique_together={('supervisor', 'endorsement')},
        ),
    ]
