# Generated by Django 5.1.2 on 2025-10-18 12:03

from django.db import migrations, models
from django.db.models import deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auditlog_disconnectionrequest_message_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # AuditLog model already created in migration 0030, so this is a no-op
        # The table already exists, so we skip creating it again
    ]
