# Generated by Django 5.1.2 on 2025-10-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_add_audit_log_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aope_area',
            field=models.CharField(blank=True, help_text='Area of Practice Endorsement area', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='board_variation_document',
            field=models.FileField(blank=True, help_text='Uploaded board approval document for variations', null=True, upload_to='board_variations/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='board_variation_enabled',
            field=models.BooleanField(default=False, help_text='Whether board has approved variations to standard requirements'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='direct_contact_requirement',
            field=models.IntegerField(default=176, help_text='Annual direct contact hours requirement (default 176 for registrars)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fte_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Full-time equivalent percentage (100 = full-time)', max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='general_registration_number',
            field=models.CharField(blank=True, help_text='AHPRA general registration number (for registrars)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='indigenous_identity',
            field=models.CharField(choices=[('ABORIGINAL', 'Aboriginal'), ('TORRES_STRAIT', 'Torres Strait Islander'), ('BOTH', 'Both Aboriginal and Torres Strait Islander'), ('NEITHER', 'Neither'), ('PREFER_NOT', 'Prefer not to say')], default='NEITHER', help_text='Cultural identity for cultural supervision eligibility', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leave_carer_weeks',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Carer leave taken (in weeks)', max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leave_lifestyle_weeks',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lifestyle leave taken (in weeks)', max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leave_parental_weeks',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Parental leave taken (in weeks)', max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leave_sick_weeks',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sick leave taken (in weeks)', max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postgrad_qualification',
            field=models.CharField(blank=True, help_text='Postgraduate qualification details', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registrar_track',
            field=models.CharField(blank=True, choices=[('SIXTH_YEAR', 'Track 1 - Sixth-year (MPsych/bridging)'), ('SIXTH_PHD', 'Track 2 - Sixth + Doctoral'), ('SEVENTH_YEAR', 'Track 3 - Seventh-year (DPsych/PsyD)')], help_text='Registrar program track (SIXTH_YEAR, SIXTH_PHD, SEVENTH_YEAR)', max_length=20, null=True),
        ),
    ]
