# Generated by Django 5.1.2 on 2025-10-19 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('PROVISIONAL', 'Provisional Psychologist'), ('REGISTRAR', 'Registrar'), ('SUPERVISOR', 'Supervisor'), ('ORG_ADMIN', 'Organisation Administrator')], help_text='Program type this configuration applies to', max_length=32)),
                ('report_type', models.CharField(help_text='Type of report (e.g., MIDPOINT, FINAL, QUARTERLY)', max_length=32)),
                ('report_label', models.CharField(help_text='Display name for this report type', max_length=100)),
                ('trigger_condition', models.JSONField(help_text="Condition that triggers this report (e.g., {'type': 'percentage', 'value': 50})")),
                ('due_offset_days', models.IntegerField(default=0, help_text='Days after trigger condition to set as due date')),
                ('is_required', models.BooleanField(default=True, help_text='Whether this report is mandatory')),
                ('allows_draft', models.BooleanField(default=True, help_text='Whether trainees can save drafts')),
                ('requires_all_competencies', models.BooleanField(default=True, help_text='Whether all competencies must be rated')),
                ('supervisor_approval_required', models.BooleanField(default=True, help_text='Whether supervisor approval is required')),
                ('can_request_revision', models.BooleanField(default=True, help_text='Whether supervisor can request revisions')),
                ('instructions', models.TextField(blank=True, help_text='Instructions for completing this report')),
            ],
            options={
                'ordering': ['program_type', 'report_type'],
                'unique_together': {('program_type', 'report_type')},
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REQUIRES_REVISION', 'Requires Revision')], default='DRAFT', help_text='Current status of the report', max_length=32)),
                ('reporting_period_start', models.DateField(help_text='Start date of the reporting period')),
                ('reporting_period_end', models.DateField(help_text='End date of the reporting period')),
                ('submission_date', models.DateTimeField(blank=True, help_text='When the report was submitted for review', null=True)),
                ('due_date', models.DateField(help_text='When the report is due')),
                ('competency_ratings', models.JSONField(default=dict, help_text="Competency ratings: {'C1': {'milestone': 'M3', 'reflection': '...'}}")),
                ('achievements', models.TextField(blank=True, help_text='Key achievements during the reporting period')),
                ('challenges', models.TextField(blank=True, help_text='Challenges faced during the reporting period')),
                ('learning_goals', models.TextField(blank=True, help_text='Learning goals for the next period')),
                ('support_needed', models.TextField(blank=True, help_text='Support or resources needed')),
                ('additional_comments', models.TextField(blank=True, help_text='Any additional comments')),
                ('supervisor_comments', models.TextField(blank=True, help_text='Overall supervisor comments')),
                ('supervisor_recommendations', models.TextField(blank=True, help_text='Supervisor recommendations for next period')),
                ('competency_feedback', models.JSONField(default=dict, help_text="Supervisor feedback per competency: {'C1': 'Excellent progress...'}")),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the supervisor completed their review', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(blank=True, help_text='Supervisor assigned to review this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_reports', to=settings.AUTH_USER_MODEL)),
                ('trainee', models.ForeignKey(help_text='Trainee who created this report', on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to=settings.AUTH_USER_MODEL)),
                ('report_config', models.ForeignKey(help_text='Configuration used for this report', on_delete=django.db.models.deletion.PROTECT, to='progress_reports.progressreportconfig')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trainee', 'status'], name='progress_re_trainee_cbce6f_idx'), models.Index(fields=['supervisor', 'status'], name='progress_re_supervi_6892a9_idx'), models.Index(fields=['due_date'], name='progress_re_due_dat_889069_idx')],
            },
        ),
    ]
