# Generated by Django 5.1.2 on 2025-10-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_aope', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarProgramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('TRACK_1', 'Track 1: 2 years FTE'), ('TRACK_2', 'Track 2: 3 years FTE'), ('TRACK_3', 'Track 3: 4 years FTE')], max_length=10, unique=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('duration_years', models.IntegerField()),
                ('total_hours_required', models.IntegerField(default=2000)),
                ('direct_contact_annual_hours', models.IntegerField(default=176)),
                ('supervision_hours_required', models.IntegerField()),
                ('cpd_hours_required', models.IntegerField()),
                ('active_cpd_percentage', models.FloatField(default=0.5)),
                ('peer_consultation_hours', models.IntegerField(default=10)),
                ('principal_supervisor_min_percentage', models.FloatField(default=50.0)),
                ('individual_supervision_min_percentage', models.FloatField(default=66.6)),
                ('short_session_max_hours', models.IntegerField(default=10)),
                ('short_session_threshold_minutes', models.IntegerField(default=60)),
                ('direct_supervision_hours_per_fte', models.IntegerField(default=40)),
                ('observation_frequency_days', models.IntegerField(default=180)),
                ('observation_warning_days', models.IntegerField(default=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registrar Program Configuration',
                'verbose_name_plural': 'Registrar Program Configurations',
            },
        ),
    ]
