# Generated by Django 5.1.2 on 2025-09-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_ahpra_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='signature_url',
            field=models.TextField(blank=True, help_text='Signature image (data URL or path)'),
        ),
    ]
