# Generated by Django 5.1.2 on 2025-09-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_aope_userprofile_program_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='principal_supervisor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondary_supervisor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='supervisor_emails',
            field=models.TextField(blank=True, help_text='Additional supervisor email addresses, one per line'),
        ),
    ]
