# Generated by Django 5.1.2 on 2025-09-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_supervisor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='supervisor_welcome_seen',
            field=models.BooleanField(default=False, help_text='Whether the supervisor has seen the welcome overlay'),
        ),
    ]
