# Generated by Django 5.1.2 on 2025-09-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_supervisor_welcome_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='supervisor_registration_date',
            field=models.DateField(blank=True, help_text='Date when the user was approved as a supervisor by the Psychology Board', null=True),
        ),
    ]
