# Generated by Django 5.1.2 on 2025-09-16 00:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionAEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('client_contact', 'Client Contact'), ('simulated_contact', 'Simulated Client Contact'), ('independent_activity', 'Independent Client Related Activity')], default='client_contact', max_length=20)),
                ('date', models.DateField()),
                ('client_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('client_pseudonym', models.CharField(help_text='e.g., BM-1961-M', max_length=50)),
                ('activity_description', models.TextField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reflection', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_a_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Section A Entry',
                'verbose_name_plural': 'Section A Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
