# Generated by Django 5.1.2 on 2025-09-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_a', '0004_sectionaentry_parent_dcc_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionaentry',
            name='simulated',
            field=models.BooleanField(default=False, help_text='True if this is a simulated client contact (SDCC)'),
        ),
    ]
