# Generated by Django 5.1.2 on 2025-09-17 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_userprofile_organization_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_supervision', models.DateField()),
                ('supervisor_name', models.CharField(max_length=255)),
                ('supervisor_type', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('SECONDARY', 'Secondary')], max_length=20)),
                ('supervision_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group'), ('OTHER', 'Other')], max_length=20)),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes')),
                ('summary', models.TextField(help_text='Supervision summary and key points discussed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_entries', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'Supervision Entry',
                'verbose_name_plural': 'Supervision Entries',
                'ordering': ['-date_of_supervision', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupervisionWeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_starting', models.DateField()),
                ('week_total_minutes', models.IntegerField(default=0)),
                ('cumulative_total_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_weekly_summaries', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'Supervision Weekly Summary',
                'verbose_name_plural': 'Supervision Weekly Summaries',
                'ordering': ['-week_starting'],
                'unique_together': {('trainee', 'week_starting')},
            },
        ),
    ]
