version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: psychpath
      POSTGRES_USER: psychpath
      POSTGRES_PASSWORD: psychpath
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=psychpath
      - DB_USER=psychpath
      - DB_PASSWORD=psychpath
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,testserver,backend
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: bash -lc "python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

volumes:
  pgdata:
