# Generated by Django 5.1.2 on 2025-09-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0006_alter_logbookauditlog_action_unlockrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlockrequest',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration of unlock in minutes', null=True),
        ),
        migrations.AddField(
            model_name='unlockrequest',
            name='manually_relocked',
            field=models.BooleanField(default=False, help_text='Whether manually re-locked before expiry'),
        ),
        migrations.AddField(
            model_name='unlockrequest',
            name='unlock_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the unlock expires', null=True),
        ),
        migrations.AlterField(
            model_name='logbookauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('unlocked', 'Unlocked'), ('locked', 'Locked'), ('resubmitted', 'Resubmitted'), ('message_sent', 'Message Sent'), ('entry_edited', 'Entry Edited'), ('comment_added', 'Comment Added'), ('comment_replied', 'Comment Replied'), ('comment_edited', 'Comment Edited'), ('comment_deleted', 'Comment Deleted'), ('comment_viewed', 'Comment Viewed'), ('response_added', 'Response Added'), ('unlock_requested', 'Unlock Requested'), ('unlock_approved', 'Unlock Approved'), ('unlock_denied', 'Unlock Denied'), ('unlock_activated', 'Unlock Activated'), ('unlock_expired', 'Unlock Expired'), ('unlock_force_relocked', 'Unlock Force Re-locked')], max_length=25),
        ),
    ]
