# Generated by Django 5.1.2 on 2025-09-19 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0007_unlockrequest_duration_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dccentry',
            name='logbook',
        ),
        migrations.RemoveField(
            model_name='pdentry',
            name='logbook',
        ),
        migrations.RemoveField(
            model_name='supentry',
            name='logbook',
        ),
        migrations.RemoveField(
            model_name='weeklylogbook',
            name='cumulative_cra_hours',
        ),
        migrations.RemoveField(
            model_name='weeklylogbook',
            name='cumulative_dcc_hours',
        ),
        migrations.RemoveField(
            model_name='weeklylogbook',
            name='cumulative_pd_hours',
        ),
        migrations.RemoveField(
            model_name='weeklylogbook',
            name='cumulative_sup_hours',
        ),
        migrations.RemoveField(
            model_name='weeklylogbook',
            name='cumulative_total_hours',
        ),
        migrations.RemoveField(
            model_name='weeklylogbook',
            name='total_cra_hours',
        ),
        migrations.RemoveField(
            model_name='weeklylogbook',
            name='total_dcc_hours',
        ),
        migrations.RemoveField(
            model_name='weeklylogbook',
            name='total_pd_hours',
        ),
        migrations.RemoveField(
            model_name='weeklylogbook',
            name='total_sup_hours',
        ),
        migrations.RemoveField(
            model_name='weeklylogbook',
            name='total_weekly_hours',
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='week_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='logbookauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('unlocked', 'Unlocked'), ('locked', 'Locked'), ('resubmitted', 'Resubmitted'), ('message_sent', 'Message Sent'), ('entry_edited', 'Entry Edited'), ('comment_added', 'Comment Added'), ('comment_replied', 'Comment Replied'), ('comment_edited', 'Comment Edited'), ('comment_deleted', 'Comment Deleted'), ('comment_viewed', 'Comment Viewed'), ('response_added', 'Response Added'), ('unlock_requested', 'Unlock Requested'), ('unlock_approved', 'Unlock Approved'), ('unlock_denied', 'Unlock Denied'), ('unlock_activated', 'Unlock Activated'), ('unlock_expired', 'Unlock Expired'), ('unlock_force_relocked', 'Unlock Force Re-locked'), ('notification_sent', 'Notification Sent')], max_length=25),
        ),
        migrations.AlterField(
            model_name='weeklylogbook',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklylogbook',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('logbook_submitted', 'Logbook Submitted'), ('logbook_status_updated', 'Logbook Status Updated'), ('comment_added', 'Comment Added'), ('unlock_requested', 'Unlock Requested'), ('unlock_approved', 'Unlock Approved'), ('unlock_denied', 'Unlock Denied'), ('unlock_expiry_warning', 'Unlock Expiry Warning'), ('supervision_invite_pending', 'Supervision Invite Pending'), ('system_message', 'System Message')], max_length=30)),
                ('payload', models.JSONField(default=dict, help_text='Additional data for the notification')),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CRAEntry',
        ),
        migrations.DeleteModel(
            name='DCCEntry',
        ),
        migrations.DeleteModel(
            name='PDEntry',
        ),
        migrations.DeleteModel(
            name='SUPEntry',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', '-created_at'], name='logbook_app_user_id_50c0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='logbook_app_notific_a01c09_idx'),
        ),
    ]
