# Generated by Django 5.1.2 on 2025-10-04 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0009_remove_commentthread_logbook_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, help_text='Direct link to related page', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('logbook_submission', 'Logbook Submission'), ('logbook_approved', 'Logbook Approved'), ('logbook_rejected', 'Logbook Rejected'), ('logbook_returned', 'Logbook Returned for Edits'), ('supervision_invite', 'Supervision Invitation'), ('supervision_accepted', 'Supervision Accepted'), ('supervision_rejected', 'Supervision Rejected'), ('system_alert', 'System Alert')], default='system_alert', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read', '-created_at'], name='logbook_app_recipient_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='logbook_app_type_idx'),
        ),
    ]
