# Generated by Django 5.1.2 on 2025-09-15 20:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyLogbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to Supervisor'), ('approved', 'Approved by Supervisor'), ('rejected', 'Rejected by Supervisor'), ('locked', 'Locked (Final)')], default='draft', max_length=20)),
                ('total_dcc_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_cra_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_pd_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_sup_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_weekly_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cumulative_dcc_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cumulative_cra_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cumulative_pd_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cumulative_sup_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cumulative_total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_logbooks', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_logbooks', to=settings.AUTH_USER_MODEL)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('trainee', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='SUPEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('client_issue', models.CharField(max_length=200)),
                ('activity_description', models.TextField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('reflection', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='logbook_app.weeklylogbook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PDEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('client_issue', models.CharField(max_length=200)),
                ('activity_description', models.TextField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('reflection', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='logbook_app.weeklylogbook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogbookAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('unlocked', 'Unlocked'), ('locked', 'Locked')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='logbook_app.weeklylogbook')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DCCEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('client_issue', models.CharField(max_length=200)),
                ('activity_description', models.TextField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('reflection', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='logbook_app.weeklylogbook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CRAEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('client_issue', models.CharField(max_length=200)),
                ('activity_description', models.TextField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('reflection', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='logbook_app.weeklylogbook')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
