# Generated by Django 5.1.2 on 2025-09-19 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0002_weeklylogbook_section_a_entry_ids_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logbookauditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional structured information'),
        ),
        migrations.AddField(
            model_name='logbookauditlog',
            name='target_id',
            field=models.CharField(blank=True, help_text='ID of entry or message if applicable', max_length=100),
        ),
        migrations.AddField(
            model_name='logbookauditlog',
            name='user_role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('trainee', 'Trainee'), ('admin', 'Admin'), ('system', 'System')], default='trainee', max_length=20),
        ),
        migrations.AlterField(
            model_name='logbookauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('unlocked', 'Unlocked'), ('locked', 'Locked'), ('resubmitted', 'Resubmitted'), ('message_sent', 'Message Sent'), ('entry_edited', 'Entry Edited'), ('comment_added', 'Comment Added'), ('response_added', 'Response Added')], max_length=20),
        ),
        migrations.CreateModel(
            name='LogbookMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(choices=[('supervisor', 'Supervisor'), ('trainee', 'Trainee'), ('admin', 'Admin'), ('system', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='logbook_app.weeklylogbook')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
