# Generated by Django 5.1.2 on 2025-09-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0004_commentthread_commentmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmessage',
            name='locked',
            field=models.BooleanField(default=False, help_text='True once viewed by the other party'),
        ),
        migrations.AddField(
            model_name='commentmessage',
            name='seen_by',
            field=models.JSONField(default=list, help_text='User IDs who have viewed this comment'),
        ),
        migrations.AddField(
            model_name='commentmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commentmessage',
            name='author_role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('provisional', 'Provisional Psychologist'), ('registrar', 'Registrar Psychologist'), ('org_admin', 'Organization Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='logbookauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('unlocked', 'Unlocked'), ('locked', 'Locked'), ('resubmitted', 'Resubmitted'), ('message_sent', 'Message Sent'), ('entry_edited', 'Entry Edited'), ('comment_added', 'Comment Added'), ('comment_replied', 'Comment Replied'), ('comment_edited', 'Comment Edited'), ('comment_deleted', 'Comment Deleted'), ('comment_viewed', 'Comment Viewed'), ('response_added', 'Response Added')], max_length=20),
        ),
        migrations.AlterField(
            model_name='logbookauditlog',
            name='user_role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('provisional', 'Provisional Psychologist'), ('registrar', 'Registrar Psychologist'), ('org_admin', 'Organization Admin'), ('system', 'System')], default='provisional', max_length=20),
        ),
        migrations.AlterField(
            model_name='logbookmessage',
            name='author_role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('provisional', 'Provisional Psychologist'), ('registrar', 'Registrar Psychologist'), ('org_admin', 'Organization Admin')], max_length=20),
        ),
    ]
