# Generated by Django 5.1.2 on 2025-09-20 06:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0008_remove_dccentry_logbook_remove_pdentry_logbook_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentthread',
            name='logbook',
        ),
        migrations.RemoveField(
            model_name='logbookmessage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='logbookmessage',
            name='logbook',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='unlockrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='unlockrequest',
            name='logbook',
        ),
        migrations.RemoveField(
            model_name='unlockrequest',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='unlockrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='logbookauditlog',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='logbookauditlog',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='logbookauditlog',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='weeklylogbook',
            name='section_a_entry_ids',
        ),
        migrations.RemoveField(
            model_name='weeklylogbook',
            name='section_b_entry_ids',
        ),
        migrations.RemoveField(
            model_name='weeklylogbook',
            name='section_c_entry_ids',
        ),
        migrations.RemoveField(
            model_name='weeklylogbook',
            name='week_number',
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='cumulative_cra_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='cumulative_dcc_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='cumulative_pd_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='cumulative_sup_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='cumulative_total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='total_cra_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='total_dcc_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='total_pd_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='total_sup_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='total_weekly_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='logbookauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('unlocked', 'Unlocked'), ('locked', 'Locked')], max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklylogbook',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to Supervisor'), ('approved', 'Approved by Supervisor'), ('rejected', 'Rejected by Supervisor'), ('locked', 'Locked (Final)')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklylogbook',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logbooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CRAEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('client_issue', models.CharField(max_length=200)),
                ('activity_description', models.TextField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('reflection', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='logbook_app.weeklylogbook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DCCEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('client_issue', models.CharField(max_length=200)),
                ('activity_description', models.TextField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('reflection', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='logbook_app.weeklylogbook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PDEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('client_issue', models.CharField(max_length=200)),
                ('activity_description', models.TextField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('reflection', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='logbook_app.weeklylogbook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SUPEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('client_issue', models.CharField(max_length=200)),
                ('activity_description', models.TextField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('reflection', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='logbook_app.weeklylogbook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CommentMessage',
        ),
        migrations.DeleteModel(
            name='CommentThread',
        ),
        migrations.DeleteModel(
            name='LogbookMessage',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UnlockRequest',
        ),
    ]
