# Generated by Django 5.1.2 on 2025-10-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epas', '0002_add_epa_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epa',
            name='code',
            field=models.CharField(help_text='EPA code (e.g., C5-07)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='epa',
            name='description',
            field=models.TextField(help_text='Brief summary of the EPA'),
        ),
        migrations.AlterField(
            model_name='epa',
            name='descriptors',
            field=models.JSONField(help_text="List of competency descriptors this EPA demonstrates (e.g., ['5.1', '5.3'])"),
        ),
        migrations.AlterField(
            model_name='epa',
            name='title',
            field=models.CharField(help_text='EPA title', max_length=500),
        ),
    ]
