# Generated by Django 5.1.2 on 2025-10-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency',
            name='code',
            field=models.CharField(help_text='Competency code (e.g., C1, C2)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='competency',
            name='description',
            field=models.TextField(help_text='Core summary description'),
        ),
        migrations.AlterField(
            model_name='competency',
            name='descriptors',
            field=models.JSONField(help_text='List of competency descriptors'),
        ),
        migrations.AlterField(
            model_name='competency',
            name='title',
            field=models.CharField(help_text='Competency title', max_length=500),
        ),
    ]
