# Generated by Django 5.1.2 on 2025-09-18 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyLogbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_starting', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('returned', 'Returned for revision')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('returned_reason', models.TextField(blank=True)),
                ('dcc_minutes', models.IntegerField(default=0)),
                ('cra_minutes', models.IntegerField(default=0)),
                ('pd_minutes', models.IntegerField(default=0)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrar_weeks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_starting'],
                'unique_together': {('trainee', 'week_starting')},
            },
        ),
        migrations.CreateModel(
            name='RegistrarLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Store duration in minutes')),
                ('category', models.CharField(choices=[('direct_client_contact', 'Direct Client Contact'), ('client_related_activity', 'Client Related Activity'), ('professional_development', 'Professional Development')], max_length=40)),
                ('short_description', models.CharField(max_length=255)),
                ('reflection', models.TextField()),
                ('aope', models.CharField(blank=True, help_text='Optional AoPE alignment tag', max_length=100)),
                ('program_type', models.CharField(default='registrar', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrar_entries', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='registrar_logbook.weeklylogbook')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
