# Generated by Django 5.1.2 on 2025-10-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_logbook', '0003_add_practice_entry_model'),
    ]

    operations = [
        # RegistrarPracticeEntry table structure already correct from SQL script
        # This migration is a no-op to avoid conflicts with manually created table
    ]
