# Generated by Django 5.1.2 on 2025-10-07 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_logbook', '0003_add_practice_entry_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='registrar_l_program_6743a8_idx',
            old_name='registrar_au_program_8c4b7d_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='registrar_l_actor_i_2771b8_idx',
            old_name='registrar_au_actor_i_5b8f8e_idx',
        ),
        migrations.RenameIndex(
            model_name='registrarpracticeentry',
            new_name='registrar_l_program_189adc_idx',
            old_name='idx_rpe_program_date',
        ),
        migrations.RenameIndex(
            model_name='registrarpracticeentry',
            new_name='registrar_l_program_11d327_idx',
            old_name='idx_rpe_program_dcc',
        ),
        migrations.AlterField(
            model_name='registrarprogram',
            name='fte_fraction',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Full-time equivalent fraction', max_digits=3),
        ),
        migrations.AddIndex(
            model_name='registrarpracticeentry',
            index=models.Index(fields=['program', 'competency_tags'], name='registrar_l_program_ed67a0_idx'),
        ),
    ]
