# Generated by Django 5.1.2 on 2025-10-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_add_context_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_QA', 'In QA'), ('READY_FOR_PROD', 'Ready for Prod'), ('RELEASED', 'Released')], default='DRAFT', max_length=20)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('checklist_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_sup_stage_4e9f41_idx',
            old_name='support_sup_stage_1d2e9f_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_sup_ticket__81d2cb_idx',
            old_name='support_sup_ticket__2b5a0a_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_sup_target__2f825c_idx',
            old_name='support_sup_target__d9b61b_idx',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='promoted_to_release',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='qa_status',
            field=models.CharField(choices=[('NOT_TESTED', 'Not Tested'), ('IN_QA', 'In QA'), ('PASSED', 'Passed'), ('REJECTED', 'Rejected')], default='NOT_TESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='related_tickets',
            field=models.ManyToManyField(blank=True, to='support.supportticket'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='test_plan',
            field=models.JSONField(blank=True, default=dict, help_text='\n    {\n      "preconditions": "",\n      "test_cases": [\n        {\n          "description": "",\n          "steps": [],\n          "expected_result": "",\n          "actual_result": "",\n          "status": "NOT_TESTED|PASSED|FAILED"\n        }\n      ]\n    }\n    '),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('REGISTER', 'User Registration'), ('PROFILE_UPDATE', 'Profile Update'), ('PD_ENTRY', 'PD Entry Created/Updated'), ('SUPERVISION_ENTRY', 'Supervision Entry Created/Updated'), ('SECTION_A_ENTRY', 'Section A Entry Created/Updated'), ('PASSWORD_RESET', 'Password Reset'), ('EMAIL_VERIFICATION', 'Email Verification'), ('SECTION_A_CREATE', 'Section A Entry Created'), ('SECTION_A_UPDATE', 'Section A Entry Updated'), ('SECTION_A_DELETE', 'Section A Entry Deleted'), ('SECTION_B_CREATE', 'Section B Entry Created'), ('SECTION_B_UPDATE', 'Section B Entry Updated'), ('SECTION_B_DELETE', 'Section B Entry Deleted'), ('SECTION_C_CREATE', 'Section C Entry Created'), ('SECTION_C_UPDATE', 'Section C Entry Updated'), ('SECTION_C_DELETE', 'Section C Entry Deleted'), ('LOGBOOK_CREATE', 'Logbook Created'), ('LOGBOOK_UPDATE', 'Logbook Updated'), ('LOGBOOK_DELETE', 'Logbook Deleted'), ('MEETING_CREATE', 'Meeting Created'), ('MEETING_UPDATE', 'Meeting Updated'), ('MEETING_DELETE', 'Meeting Deleted')], max_length=50),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_tickets', to='support.release'),
        ),
    ]
