# Generated by Django 5.1.2 on 2025-09-16 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_a', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionaentry',
            options={'ordering': ['-session_date', '-created_at'], 'verbose_name': 'Section A Entry', 'verbose_name_plural': 'Section A Entries'},
        ),
        migrations.RemoveField(
            model_name='sectionaentry',
            name='date',
        ),
        migrations.AddField(
            model_name='sectionaentry',
            name='client_id',
            field=models.CharField(blank=True, help_text='Client pseudonym e.g., LN-1985-M', max_length=50),
        ),
        migrations.AddField(
            model_name='sectionaentry',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='sectionaentry',
            name='place_of_practice',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sectionaentry',
            name='presenting_issues',
            field=models.TextField(blank=True, help_text='Detailed description of presenting issues'),
        ),
        migrations.AddField(
            model_name='sectionaentry',
            name='reflections_on_experience',
            field=models.TextField(blank=True, help_text='Reflections on the experience'),
        ),
        migrations.AddField(
            model_name='sectionaentry',
            name='session_activity_type',
            field=models.CharField(blank=True, choices=[('evaluation', 'Evaluation'), ('intervention', 'Intervention'), ('assessment', 'Assessment'), ('consultation', 'Consultation'), ('supervision', 'Supervision'), ('other', 'Other')], default='evaluation', max_length=20),
        ),
        migrations.AddField(
            model_name='sectionaentry',
            name='session_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionaentry',
            name='week_starting',
            field=models.DateField(blank=True, help_text='Week starting date for this session', null=True),
        ),
        migrations.AlterField(
            model_name='sectionaentry',
            name='activity_description',
            field=models.TextField(blank=True, help_text='Legacy field'),
        ),
        migrations.AlterField(
            model_name='sectionaentry',
            name='client_age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='sectionaentry',
            name='client_pseudonym',
            field=models.CharField(blank=True, help_text='Legacy field', max_length=50),
        ),
        migrations.AlterField(
            model_name='sectionaentry',
            name='duration_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy field', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sectionaentry',
            name='reflection',
            field=models.TextField(blank=True, help_text='Legacy field'),
        ),
    ]
