# Generated by Django 5.1.2 on 2025-09-16 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_a', '0002_alter_sectionaentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionaentry',
            name='session_activity_types',
            field=models.JSONField(default=list, help_text='List of selected activity types (standard and custom)'),
        ),
        migrations.CreateModel(
            name='CustomSessionActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Custom activity type name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_activity_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('trainee', 'name')},
            },
        ),
    ]
