# Generated by Django 5.1.2 on 2025-09-16 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_a', '0003_sectionaentry_session_activity_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionaentry',
            name='parent_dcc_entry',
            field=models.ForeignKey(blank=True, help_text='Parent DCC entry for CRA entries', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cra_entries', to='section_a.sectionaentry'),
        ),
        migrations.AlterField(
            model_name='sectionaentry',
            name='entry_type',
            field=models.CharField(choices=[('client_contact', 'Client Contact'), ('simulated_contact', 'Simulated Client Contact'), ('independent_activity', 'Independent Client Related Activity'), ('cra', 'Client Related Activity')], default='client_contact', max_length=20),
        ),
    ]
