# Generated by Django 5.1.2 on 2025-09-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_a', '0005_sectionaentry_simulated'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionaentry',
            name='locked',
            field=models.BooleanField(default=False, help_text='True if this entry is part of a submitted logbook'),
        ),
    ]
