# Generated by Django 5.1.2 on 2025-09-20 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section_a', '0007_sectionaentry_supervisor_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionaentry',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='sectionaentry',
            name='supervisor_comment',
        ),
        migrations.RemoveField(
            model_name='sectionaentry',
            name='trainee_response',
        ),
    ]
