# Generated by Django 5.1.2 on 2025-10-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_a', '0008_remove_sectionaentry_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionaentry',
            name='locked',
            field=models.BooleanField(default=False, help_text='True if this entry is part of a submitted logbook'),
        ),
        migrations.AddField(
            model_name='sectionaentry',
            name='supervisor_comment',
            field=models.TextField(blank=True, default='', help_text='Supervisor comment for this entry when reviewing a logbook'),
        ),
        migrations.AddField(
            model_name='sectionaentry',
            name='trainee_response',
            field=models.TextField(blank=True, default='', help_text='Trainee response to supervisor comment when resubmitting'),
        ),
    ]
