# Generated by Django 5.1.2 on 2025-10-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_a', '0009_sectionaentry_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionaentry',
            name='activity_type',
            field=models.CharField(blank=True, help_text='CRA activity type', max_length=100),
        ),
        migrations.AddField(
            model_name='sectionaentry',
            name='custom_activity_type',
            field=models.CharField(blank=True, help_text='Custom CRA activity type', max_length=100),
        ),
    ]
