# Generated by Django 5.1.2 on 2025-10-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_a', '0009_remove_extra_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionaentry',
            name='additional_comments',
            field=models.TextField(blank=True, help_text='Additional comments or observations'),
        ),
    ]
