# Generated by Django 5.1.2 on 2025-10-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_a', '0010_add_additional_comments_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionaentry',
            name='session_modality',
            field=models.CharField(choices=[('face_to_face', 'Face-to-Face'), ('video', 'Video/Telehealth'), ('phone', 'Phone'), ('hybrid', 'Hybrid')], default='face_to_face', help_text='Mode of session delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionaentry',
            name='additional_comments',
            field=models.TextField(blank=True, help_text='Additional comments or observations (max 1000 characters)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sectionaentry',
            name='client_id',
            field=models.CharField(blank=True, help_text='Client pseudonym (max 50 characters)', max_length=50),
        ),
        migrations.AlterField(
            model_name='sectionaentry',
            name='place_of_practice',
            field=models.CharField(blank=True, help_text='Location of practice (max 200 characters)', max_length=200),
        ),
        migrations.AlterField(
            model_name='sectionaentry',
            name='presenting_issues',
            field=models.TextField(blank=True, help_text='Detailed description of presenting issues (max 2000 characters)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='sectionaentry',
            name='reflections_on_experience',
            field=models.TextField(blank=True, help_text='Reflections on the experience (max 3000 characters)', max_length=3000),
        ),
    ]
