# Generated by Django 5.1.2 on 2025-10-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_a', '0011_add_session_modality_and_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionaentry',
            name='counts_toward_total',
            field=models.BooleanField(default=True, help_text="Whether this entry counts toward total hours (simulated >60h don't count)"),
        ),
    ]
