# Generated by Django 5.1.2 on 2025-10-19 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0032_add_ahpra_compliance_fields'),
        ('section_a', '0012_sectionaentry_counts_toward_total'),
        ('section_b', '0007_professionaldevelopmententry_supervisor_initials'),
        ('section_c', '0009_supervisionentry_is_registrar_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('SECTION_A', 'Direct Client Contact (Section A)'), ('SECTION_B', 'Professional Development (Section B)'), ('SECTION_C', 'Supervision Session (Section C)'), ('PRACTICE_LOG', 'Practice Log (Registrar)'), ('MANUAL', 'Manual Entry')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('milestone_level', models.CharField(choices=[('M1', 'M1 - Novice'), ('M2', 'M2 - Developing'), ('M3', 'M3 - Proficient'), ('M4', 'M4 - Advanced')], default='M2', max_length=2)),
                ('reflection', models.TextField(blank=True)),
                ('supervisor_validated', models.BooleanField(default=False)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('suggested_by_epa', models.CharField(blank=True, help_text='EPA code that suggested this link', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competency_tracking.competencydefinition')),
                ('section_a_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section_a.sectionaentry')),
                ('section_b_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section_b.professionaldevelopmententry')),
                ('section_c_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section_c.supervisionentry')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_evidence', to='api.userprofile')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_evidence', to='api.userprofile')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_milestone', models.CharField(choices=[('M1', 'M1 - Novice'), ('M2', 'M2 - Developing'), ('M3', 'M3 - Proficient'), ('M4', 'M4 - Advanced')], max_length=2)),
                ('evidence_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competency_tracking.competencydefinition')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
            options={
                'ordering': ['competency__order', 'competency__code'],
                'unique_together': {('trainee', 'competency')},
            },
        ),
    ]
