# Generated by Django 5.1.2 on 2025-10-22 10:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0033_competency_alter_epa_options_alter_milestone_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySupervisionAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_starting', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_agendas', to='api.userprofile')),
            ],
            options={
                'ordering': ['-week_starting', '-created_at'],
                'indexes': [models.Index(fields=['trainee', 'week_starting'], name='supervision_trainee_12d124_idx')],
                'unique_together': {('trainee', 'week_starting')},
            },
        ),
    ]
