# Generated by Django 5.1.2 on 2025-10-22 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision_agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('detail', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('discussed', 'Discussed'), ('carried', 'Carried forward'), ('discarded', 'Discarded')], default='open', max_length=12)),
                ('source_type', models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('FREE', 'Free-typed')], default='FREE', max_length=8)),
                ('source_entry_id', models.IntegerField(blank=True, null=True)),
                ('source_field', models.CharField(blank=True, default='', max_length=120)),
                ('source_excerpt', models.TextField(blank=True, default='')),
                ('my_reflection', models.TextField(blank=True, default='')),
                ('discussed_on', models.DateField(blank=True, null=True)),
                ('imported_to_section_c', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supervision_agenda.mysupervisionagenda')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['agenda', 'status', 'imported_to_section_c'], name='supervision_agenda__6e76d4_idx')],
            },
        ),
    ]
