# Generated by Django 5.1.2 on 2025-10-22 10:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision_agenda', '0002_agendaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionCImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_c_entry_id', models.IntegerField()),
                ('snapshot_title', models.CharField(max_length=240)),
                ('snapshot_detail', models.TextField()),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_c_imports', to='supervision_agenda.agendaitem')),
            ],
            options={
                'indexes': [models.Index(fields=['section_c_entry_id'], name='supervision_section_cfde72_idx')],
            },
        ),
    ]
