# Generated by Django 5.1.2 on 2025-09-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylogbook',
            name='section_a_entry_ids',
            field=models.JSONField(default=list, help_text='List of Section A entry IDs'),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='section_b_entry_ids',
            field=models.JSONField(default=list, help_text='List of Section B entry IDs'),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='section_c_entry_ids',
            field=models.JSONField(default=list, help_text='List of Section C entry IDs'),
        ),
    ]
