# Generated by Django 5.1.2 on 2025-09-19 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0003_logbookauditlog_metadata_logbookauditlog_target_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(blank=True, help_text='Entry ID if this is an entry-specific thread', max_length=100, null=True)),
                ('entry_section', models.CharField(blank=True, help_text='Section (A, B, C) if entry-specific', max_length=20, null=True)),
                ('thread_type', models.CharField(choices=[('general', 'General Logbook Comment'), ('entry', 'Entry-Specific Comment')], default='general', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_threads', to='logbook_app.weeklylogbook')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(choices=[('supervisor', 'Supervisor'), ('trainee', 'Trainee'), ('admin', 'Admin'), ('system', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='logbook_app.commentmessage')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='logbook_app.commentthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
