# Generated by Django 5.1.2 on 2025-09-19 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0005_commentmessage_locked_commentmessage_seen_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('unlocked', 'Unlocked'), ('locked', 'Locked'), ('resubmitted', 'Resubmitted'), ('message_sent', 'Message Sent'), ('entry_edited', 'Entry Edited'), ('comment_added', 'Comment Added'), ('comment_replied', 'Comment Replied'), ('comment_edited', 'Comment Edited'), ('comment_deleted', 'Comment Deleted'), ('comment_viewed', 'Comment Viewed'), ('response_added', 'Response Added'), ('unlock_requested', 'Unlock Requested'), ('unlock_approved', 'Unlock Approved'), ('unlock_denied', 'Unlock Denied'), ('unlock_activated', 'Unlock Activated')], max_length=20),
        ),
        migrations.CreateModel(
            name='UnlockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_role', models.CharField(choices=[('supervisor', 'Supervisor'), ('provisional', 'Provisional Psychologist'), ('registrar', 'Registrar Psychologist'), ('org_admin', 'Organization Admin')], max_length=20)),
                ('reason', models.TextField(help_text='Reason for requesting unlock')),
                ('target_section', models.CharField(blank=True, help_text='Specific section or entry ID if applicable', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('reviewer_role', models.CharField(blank=True, choices=[('org_admin', 'Organization Admin'), ('supervisor', 'Supervisor')], max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, help_text='Comment from reviewer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_requests', to='logbook_app.weeklylogbook')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlock_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('logbook', 'status')},
            },
        ),
    ]
