# Generated by Django 5.1.2 on 2025-10-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0009_remove_commentthread_logbook_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Update WeeklyLogbook status choices
        migrations.AlterField(
            model_name='weeklylogbook',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('ready', 'Ready for Submission'),
                    ('submitted', 'Submitted'),
                    ('returned_for_edits', 'Returned for Edits'),
                    ('approved', 'Approved'),
                    ('rejected', 'Rejected'),
                    ('unlocked_for_edits', 'Unlocked for Editing'),
                    ('locked', 'Locked'),
                ],
                default='draft',
                max_length=20
            ),
        ),
        
        # Add missing workflow timestamps to WeeklyLogbook
        migrations.AddField(
            model_name='weeklylogbook',
            name='review_completed_at',
            field=models.DateTimeField(blank=True, help_text='When supervisor completed review of this logbook', null=True),
        ),
    ]
