# Generated by Django 5.1.2 on 2025-10-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0011_add_ahpra_fields_only'),
    ]

    operations = [
        # AHPRA fields already exist in the database
        # This migration is a no-op to avoid duplicate column creation
    ]
