# Generated by Django 5.1.2 on 2025-10-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0011_add_ahpra_fields_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylogbook',
            name='practice_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('DIRECT_REAL', 'Direct Real Client Contact'),
                    ('DIRECT_SIMULATED', 'Direct Simulated Client Contact'),
                    ('CLIENT_RELATED', 'Client-Related Activities'),
                    ('INDEPENDENT_CLIENT_RELATED', 'Independent Client-Related Activities'),
                ],
                help_text="Primary practice type for this week (Provisional 5+1 program)",
                max_length=30,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='competencies_referenced',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of competency codes (C1-C8) referenced in this week's activities"
            ),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='reflection_text',
            field=models.TextField(
                blank=True,
                help_text="Mandatory reflection for direct_real and direct_simulated practice types"
            ),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='practice_supervisor_approved',
            field=models.BooleanField(
                default=False,
                help_text="Whether supervisor has approved the practice hours for this week"
            ),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='practice_approved_at',
            field=models.DateTimeField(
                blank=True,
                help_text="When supervisor approved the practice hours",
                null=True
            ),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='simulated_hours',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Simulated skills training hours for this week (max 60 total for 5+1 program)",
                max_digits=5
            ),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='cumulative_simulated_hours',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cumulative simulated hours to date",
                max_digits=6
            ),
        ),
    ]
