# Generated by Django 5.1.2 on 2025-10-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0012_add_missing_ahpra_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dccentry',
            name='logbook',
        ),
        migrations.RemoveField(
            model_name='pdentry',
            name='logbook',
        ),
        migrations.RemoveField(
            model_name='supentry',
            name='logbook',
        ),
        migrations.DeleteModel(
            name='CRAEntry',
        ),
        migrations.DeleteModel(
            name='DCCEntry',
        ),
        migrations.DeleteModel(
            name='PDEntry',
        ),
        migrations.DeleteModel(
            name='SUPEntry',
        ),
    ]
