# Generated by Django 5.1.2 on 2025-10-19 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('logbook_app', '0013_remove_dccentry_logbook_remove_pdentry_logbook_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancedLogbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('total_dcc_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_cra_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_pd_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_supervision_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_logbooks', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_enhanced_logbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('owner', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='EnhancedLogbookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('A', 'Section A - Direct Client Contact'), ('B', 'Section B - Professional Development'), ('C', 'Section C - Supervision')], max_length=1)),
                ('title', models.CharField(max_length=100)),
                ('content_json', models.JSONField(default=dict, help_text='Stores records from that section')),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='logbook_app.enhancedlogbook')),
            ],
            options={
                'ordering': ['section_type'],
                'unique_together': {('logbook', 'section_type')},
            },
        ),
        migrations.CreateModel(
            name='EnhancedLogbookComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_id', models.UUIDField(blank=True, help_text='ID of specific record if comment is on a specific line', null=True)),
                ('text', models.TextField()),
                ('scope', models.CharField(choices=[('record', 'Record'), ('section', 'Section'), ('document', 'Document')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='logbook_app.enhancedlogbook')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='logbook_app.enhancedlogbookcomment')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='logbook_app.enhancedlogbooksection')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnhancedLogbookAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('unlocked', 'Unlocked'), ('edit_requested', 'Edit Requested'), ('edit_granted', 'Edit Granted'), ('pdf_generated', 'PDF Generated'), ('comment_added', 'Comment Added'), ('section_locked', 'Section Locked'), ('section_unlocked', 'Section Unlocked')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('diff_snapshot', models.JSONField(blank=True, help_text='Captures changed fields', null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='logbook_app.enhancedlogbook')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['logbook', '-timestamp'], name='logbook_app_logbook_24dfaf_idx'), models.Index(fields=['actor', '-timestamp'], name='logbook_app_actor_i_f6bd69_idx'), models.Index(fields=['action', '-timestamp'], name='logbook_app_action_2bcba2_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnhancedNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(choices=[('logbook_submitted', 'Logbook Submitted'), ('logbook_approved', 'Logbook Approved'), ('logbook_rejected', 'Logbook Rejected'), ('logbook_unlocked', 'Logbook Unlocked'), ('comment_added', 'Comment Added'), ('edit_requested', 'Edit Requested'), ('edit_granted', 'Edit Granted'), ('pdf_generated', 'PDF Generated')], max_length=30)),
                ('object_id', models.UUIDField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read', '-created_at'], name='logbook_app_recipie_9995c1_idx'), models.Index(fields=['notification_type'], name='logbook_app_notific_be27e5_idx')],
            },
        ),
    ]
