# Generated by Django 5.1.2 on 2025-10-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0013_add_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbookauditlog',
            name='user_role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('provisional', 'Provisional Psychologist'), ('registrar', 'Registrar Psychologist'), ('org_admin', 'Organization Admin'), ('system', 'System')], default='provisional', max_length=20),
        ),
        migrations.AddField(
            model_name='logbookauditlog',
            name='target_id',
            field=models.CharField(blank=True, help_text='ID of entry or message if applicable', max_length=100),
        ),
    ]
