# Generated by Django 5.1.2 on 2025-10-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0015_add_actor_to_enhanced_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylogbook',
            name='practice_approved_at',
            field=models.DateTimeField(blank=True, help_text='When supervisor approved the practice hours', null=True),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='simulated_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Simulated skills training hours for this week (max 60 total for 5+1 program)', max_digits=5),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='cumulative_simulated_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumulative simulated hours to date', max_digits=6),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='reflection_text',
            field=models.TextField(blank=True, help_text='Mandatory reflection for direct_real and direct_simulated practice types'),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='competencies_referenced',
            field=models.JSONField(blank=True, default=list, help_text="List of competency codes (C1-C8) referenced in this week's activities"),
        ),
    ]
