# Generated by Django 5.1.2 on 2025-10-10 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0015_commentmessage_commentthread_logbookmessage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unlockrequest',
            unique_together=set(),
        ),
    ]
