# Generated by Django 5.1.2 on 2025-10-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0016_remove_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylogbook',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('returned_for_edits', 'Returned for Edits'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('unlocked_for_edits', 'Unlocked for Editing'), ('locked', 'Locked')], default='draft', max_length=20),
        ),
    ]
