# Generated by Django 5.1.2 on 2025-10-16 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook_app', '0018_remove_under_review_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='logbook_app_recipie_31c241_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='logbook_app_type_7af6cf_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='type',
            new_name='notification_type',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='recipient',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='payload',
            field=models.JSONField(blank=True, help_text='Additional data for the notification', null=True),
        ),
        migrations.AlterField(
            model_name='weeklylogbook',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Submission'), ('submitted', 'Submitted'), ('returned_for_edits', 'Returned for Edits'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('unlocked_for_edits', 'Unlocked for Editing'), ('locked', 'Locked')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', '-created_at'], name='logbook_app_user_id_50c0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='logbook_app_notific_a01c09_idx'),
        ),
    ]
