# Generated by Django 5.1.2 on 2025-10-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_c', '0006_supervisionentry_week_starting_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisionentry',
            name='is_short_session',
            field=models.BooleanField(default=False, help_text='Session less than 60 minutes'),
        ),
        migrations.AddField(
            model_name='supervisionentry',
            name='supervision_medium',
            field=models.CharField(choices=[('IN_PERSON', 'In-Person (Visual)'), ('VIDEO', 'Video Conference (Visual)'), ('PHONE', 'Telephone (Audio Only)'), ('ASYNC', 'Asynchronous (Written)')], default='IN_PERSON', help_text='Medium of supervision delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='supervisionentry',
            name='supervisor_initials',
            field=models.CharField(blank=True, help_text='Supervisor initials confirming session', max_length=10),
        ),
    ]
