# Generated by Django 5.1.2 on 2025-10-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_c', '0006_supervisionentry_week_starting_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisionentry',
            name='locked',
            field=models.BooleanField(default=False, help_text='True if this entry is part of a submitted logbook'),
        ),
        migrations.AddField(
            model_name='supervisionentry',
            name='supervisor_comment',
            field=models.TextField(blank=True, default='', help_text='Supervisor comment for this entry when reviewing a logbook'),
        ),
        migrations.AddField(
            model_name='supervisionentry',
            name='trainee_response',
            field=models.TextField(blank=True, default='', help_text='Trainee response to supervisor comment when resubmitting'),
        ),
    ]
