# Generated by Django 5.1.2 on 2025-10-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_c', '0007_supervisionentry_is_short_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisionentry',
            name='is_cultural_supervision',
            field=models.BooleanField(default=False, help_text='Whether this supervision includes cultural considerations'),
        ),
        migrations.AddField(
            model_name='supervisionentry',
            name='locked',
            field=models.BooleanField(default=False, help_text='True if this entry is part of a submitted logbook'),
        ),
        migrations.AddField(
            model_name='supervisionentry',
            name='supervision_mode',
            field=models.CharField(choices=[('CLINICAL', 'Clinical'), ('PROFESSIONAL', 'Professional'), ('ADMINISTRATIVE', 'Administrative')], default='CLINICAL', help_text='Type of supervision provided', max_length=20),
        ),
        migrations.AddField(
            model_name='supervisionentry',
            name='supervisor_comment',
            field=models.TextField(blank=True, default='', help_text='Supervisor comment for this entry when reviewing a logbook'),
        ),
        migrations.AddField(
            model_name='supervisionentry',
            name='supervisor_is_board_approved',
            field=models.BooleanField(default=True, help_text='Whether the supervisor is board approved'),
        ),
        migrations.AddField(
            model_name='supervisionentry',
            name='trainee_response',
            field=models.TextField(blank=True, default='', help_text='Trainee response to supervisor comment when resubmitting'),
        ),
    ]
