# Generated by Django 5.1.2 on 2025-10-19 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_aope', '0001_initial'),
        ('section_c', '0008_supervisionentry_is_cultural_supervision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisionentry',
            name='is_registrar_session',
            field=models.BooleanField(default=False, help_text='Whether this is a registrar supervision session'),
        ),
        migrations.AddField(
            model_name='supervisionentry',
            name='registrar_profile',
            field=models.ForeignKey(blank=True, help_text='Link to registrar profile if this is a registrar session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervision_entries', to='registrar_aope.registrarprofile'),
        ),
    ]
