# Generated by Django 5.1.2 on 2025-10-10 11:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='settings', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Configuration Category',
                'verbose_name_plural': 'Configuration Categories',
                'db_table': 'config_categories',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('preset_data', models.JSONField(help_text='Complete configuration data')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_config.configurationcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration Preset',
                'verbose_name_plural': 'Configuration Presets',
                'db_table': 'configuration_presets',
                'ordering': ['category__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'db_table': 'system_configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('published', 'Published'), ('reverted', 'Reverted')], max_length=20)),
                ('changes', models.JSONField(default=dict, help_text='Details of what was changed')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_config.systemconfiguration')),
            ],
            options={
                'verbose_name': 'Configuration Audit Log',
                'verbose_name_plural': 'Configuration Audit Logs',
                'db_table': 'configuration_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique identifier for this config', max_length=100)),
                ('display_name', models.CharField(help_text='Human-readable name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('STRING', 'Text'), ('INTEGER', 'Number'), ('BOOLEAN', 'Yes/No'), ('JSON', 'Complex Data'), ('CHOICE', 'Dropdown Selection'), ('MULTI_CHOICE', 'Multiple Selections'), ('COLOR', 'Color'), ('ICON', 'Icon')], max_length=20)),
                ('value', models.TextField(help_text='Configuration value (JSON for complex types)')),
                ('default_value', models.TextField(blank=True)),
                ('user_roles', models.JSONField(blank=True, default=list, help_text='User roles this applies to')),
                ('contexts', models.JSONField(blank=True, default=list, help_text='UI contexts (dashboard, forms, etc.)')),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('is_required', models.BooleanField(default=False)),
                ('is_readonly', models.BooleanField(default=False)),
                ('ui_component', models.CharField(choices=[('input', 'Text Input'), ('textarea', 'Text Area'), ('select', 'Dropdown'), ('multiselect', 'Multi-Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio Buttons'), ('colorpicker', 'Color Picker'), ('iconpicker', 'Icon Picker'), ('jsoneditor', 'JSON Editor')], default='input', max_length=50)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('help_text', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_config.configurationcategory')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='system_config.systemconfiguration')),
            ],
            options={
                'verbose_name': 'Configuration Item',
                'verbose_name_plural': 'Configuration Items',
                'db_table': 'configuration_items',
                'ordering': ['category__order', 'order', 'display_name'],
                'unique_together': {('configuration', 'key')},
            },
        ),
    ]
