# Generated by Django 5.1.2 on 2025-09-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_supervisorinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ahpra_registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
