# Generated by Django 5.1.2 on 2025-09-19 02:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_supervisorendorsement'),
    ]

    operations = [
        # Drop the old supervision table
        migrations.DeleteModel(
            name='Supervision',
        ),
        # Create the new supervision table
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisee_email', models.EmailField()),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary Supervisor'), ('SECONDARY', 'Secondary Supervisor')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('verification_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisions_given', to='auth.user')),
                ('supervisee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisions_received', to='auth.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        # Create the supervision notification table
        migrations.CreateModel(
            name='SupervisionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('INVITE_SENT', 'Invite Sent'), ('REMINDER_SENT', 'Reminder Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('in_app_sent', models.BooleanField(default=False)),
                ('supervision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.supervision')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        # Add unique constraint
        migrations.AddConstraint(
            model_name='supervision',
            constraint=models.UniqueConstraint(fields=('supervisor', 'supervisee_email', 'role'), name='unique_supervision_invitation'),
        ),
    ]
