# Generated by Django 5.1.2 on 2025-09-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_supervisor_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='area_of_practice_endorsement',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='endorsement_start_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='general_registration_year',
        ),
    ]
