# Generated by Django 5.1.2 on 2025-09-21 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_initials_url_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_name', models.CharField(max_length=255)),
                ('supervisor_email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary Supervisor'), ('SECONDARY', 'Secondary Supervisor')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('provisional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_assignments', to=settings.AUTH_USER_MODEL)),
                ('supervisor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_supervisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('provisional', 'role')},
            },
        ),
    ]
