# Generated by Django 5.1.2 on 2025-09-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_prior_hours_processing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='estimated_completion_weeks',
            field=models.IntegerField(blank=True, help_text='Estimated completion time in weeks (minimum 44)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='internship_start_date',
            field=models.DateField(blank=True, help_text='Official start date of 5+1 internship', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_full_time',
            field=models.BooleanField(default=True, help_text='Whether the internship is full-time or part-time'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='provisional_registration_date',
            field=models.DateField(blank=True, help_text='Date when provisional registration was received from AHPRA', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_commitment_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Weekly commitment in hours', max_digits=4, null=True),
        ),
    ]
