# Generated by Django 5.1.2 on 2025-09-22 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_supervisorinvitation_message_and_more'),
        ('api', '0027_fix_decimal_precision'),
    ]

    operations = [
    ]
