# Generated by Django 5.1.2 on 2025-09-17 02:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PD Competency',
                'verbose_name_plural': 'PD Competencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalDevelopmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('WORKSHOP', 'Workshop'), ('WEBINAR', 'Webinar'), ('LECTURE', 'Lecture'), ('PRESENTATION', 'Presentation'), ('READING', 'Reading'), ('COURSE', 'Course'), ('CONFERENCE', 'Conference'), ('TRAINING', 'Training'), ('OTHER', 'Other')], max_length=20)),
                ('date_of_activity', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('is_active_activity', models.BooleanField(default=True)),
                ('activity_details', models.TextField(help_text='E.g. name of course, presenter, institution etc')),
                ('topics_covered', models.TextField(help_text='E.g. behavioural interventions for ADHD in adolescents')),
                ('competencies_covered', models.JSONField(default=list, help_text='List of selected competencies')),
                ('week_starting', models.DateField(help_text='Week starting date for grouping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pd_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professional Development Entry',
                'verbose_name_plural': 'Professional Development Entries',
                'ordering': ['-date_of_activity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDWeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_starting', models.DateField()),
                ('week_total_minutes', models.PositiveIntegerField(default=0)),
                ('cumulative_total_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pd_weekly_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PD Weekly Summary',
                'verbose_name_plural': 'PD Weekly Summaries',
                'ordering': ['-week_starting'],
                'unique_together': {('trainee', 'week_starting')},
            },
        ),
    ]
