# Generated by Django 5.1.2 on 2025-09-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_b', '0002_professionaldevelopmententry_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaldevelopmententry',
            name='supervisor_comment',
            field=models.TextField(blank=True, default='', help_text='Supervisor comment for this entry when reviewing a logbook'),
        ),
        migrations.AddField(
            model_name='professionaldevelopmententry',
            name='trainee_response',
            field=models.TextField(blank=True, default='', help_text='Trainee response to supervisor comment when resubmitting'),
        ),
    ]
