# Generated by Django 5.1.2 on 2025-10-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_b', '0005_professionaldevelopmententry_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaldevelopmententry',
            name='reviewed_in_supervision',
            field=models.BooleanField(default=False, help_text='Whether this PD activity has been reviewed and discussed in supervision'),
        ),
    ]
