# Generated by Django 5.1.2 on 2025-10-22 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section_b', '0007_professionaldevelopmententry_supervisor_initials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionaldevelopmententry',
            name='reviewed_in_supervision',
        ),
        migrations.RemoveField(
            model_name='professionaldevelopmententry',
            name='supervisor_initials',
        ),
    ]
