# Generated by Django 5.1.2 on 2025-10-19 10:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0032_add_ahpra_compliance_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPDCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CPD Category',
                'verbose_name_plural': 'CPD Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CPDRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PROVISIONAL', 'Provisional Psychologist'), ('REGISTRAR', 'Psychology Registrar'), ('GENERAL', 'General Registration'), ('SUPERVISOR', 'Board-Approved Supervisor')], max_length=20)),
                ('year', models.IntegerField()),
                ('total_hours_required', models.IntegerField(help_text='Total CPD hours required per year')),
                ('active_cpd_percentage', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Minimum percentage that must be active CPD', max_digits=5)),
                ('peer_consultation_hours', models.IntegerField(default=0, help_text='Required peer consultation hours per year')),
                ('requires_plan_approval', models.BooleanField(default=False, help_text='Does this role require CPD plan approval?')),
                ('requires_evidence', models.BooleanField(default=True, help_text='Does this role require evidence submission?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CPD Requirement',
                'verbose_name_plural': 'CPD Requirements',
                'ordering': ['-year', 'role'],
                'unique_together': {('role', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CPDActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the CPD activity', max_length=200)),
                ('activity_type', models.CharField(choices=[('FORMAL_LEARNING', 'Formal Learning'), ('PEER_CONSULTATION', 'Peer Consultation'), ('SUPERVISION', 'Supervision'), ('RESEARCH', 'Research'), ('TEACHING', 'Teaching/Training'), ('PROFESSIONAL_DEVELOPMENT', 'Professional Development'), ('CONFERENCE', 'Conference/Workshop'), ('ONLINE_LEARNING', 'Online Learning'), ('READING', 'Professional Reading'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(help_text='Detailed description of the activity')),
                ('activity_date', models.DateField(help_text='Date when the activity took place')),
                ('duration_hours', models.DecimalField(decimal_places=2, help_text='Duration in hours (minimum 0.25 hours)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(1000)])),
                ('delivery_mode', models.CharField(choices=[('FACE_TO_FACE', 'Face-to-Face'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid'), ('SELF_DIRECTED', 'Self-Directed'), ('GROUP', 'Group'), ('INDIVIDUAL', 'Individual')], default='FACE_TO_FACE', max_length=20)),
                ('learning_outcomes', models.TextField(blank=True, help_text='What did you learn from this activity?')),
                ('skills_developed', models.TextField(blank=True, help_text='What skills did you develop or enhance?')),
                ('application_to_practice', models.TextField(blank=True, help_text='How will you apply this learning to your practice?')),
                ('evidence_type', models.CharField(choices=[('CERTIFICATE', 'Certificate'), ('ATTENDANCE_RECORD', 'Attendance Record'), ('REFLECTION', 'Reflection'), ('ASSESSMENT', 'Assessment'), ('PORTFOLIO', 'Portfolio'), ('OTHER', 'Other')], default='REFLECTION', max_length=20)),
                ('evidence_description', models.TextField(blank=True, help_text='Description of evidence submitted')),
                ('evidence_file', models.FileField(blank=True, help_text='Upload evidence file (certificate, reflection, etc.)', null=True, upload_to='cpd_evidence/%Y/%m/')),
                ('is_active_cpd', models.BooleanField(default=True, help_text="Does this count as 'active' CPD (involves interaction, assessment, or structured learning)?")),
                ('is_peer_consultation', models.BooleanField(default=False, help_text='Is this peer consultation activity?')),
                ('is_supervision', models.BooleanField(default=False, help_text='Is this supervision-related activity?')),
                ('professional_areas', models.JSONField(blank=True, default=list, help_text='List of professional areas this activity relates to')),
                ('competencies_addressed', models.JSONField(blank=True, default=list, help_text='List of competencies this activity addresses')),
                ('quality_rating', models.IntegerField(blank=True, choices=[(1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], help_text='Rate the quality of this CPD activity (1-5 stars)', null=True)),
                ('reflection', models.TextField(blank=True, help_text='Personal reflection on the learning experience')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REQUIRES_REVISION', 'Requires Revision')], default='DRAFT', max_length=20)),
                ('reviewer_comments', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cpd_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpd_activities', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpd_activities', to='api.userprofile')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpd_portfolio.cpdcategory')),
            ],
            options={
                'verbose_name': 'CPD Activity',
                'verbose_name_plural': 'CPD Activities',
                'ordering': ['-activity_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_date'], name='cpd_portfol_user_id_0dda04_idx'), models.Index(fields=['user', 'activity_type'], name='cpd_portfol_user_id_4719c3_idx'), models.Index(fields=['user', 'is_active_cpd'], name='cpd_portfol_user_id_7f4cbc_idx'), models.Index(fields=['status'], name='cpd_portfol_status_21c8a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='CPDComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('report_period_start', models.DateField()),
                ('report_period_end', models.DateField()),
                ('total_hours_completed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active_cpd_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peer_consultation_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_hours_required', models.IntegerField()),
                ('active_cpd_percentage_required', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peer_consultation_hours_required', models.IntegerField()),
                ('is_compliant', models.BooleanField(default=False)),
                ('compliance_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('NON_COMPLIANT', 'Non-Compliant')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cpd_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpd_reports', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpd_reports', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'CPD Compliance Report',
                'verbose_name_plural': 'CPD Compliance Reports',
                'ordering': ['-year', '-created_at'],
                'unique_together': {('user', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CPDPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year this plan covers')),
                ('title', models.CharField(help_text='Title of the CPD plan', max_length=200)),
                ('description', models.TextField(help_text='Description of planned CPD activities')),
                ('learning_goals', models.TextField(help_text='What do you want to achieve this year?')),
                ('professional_areas', models.JSONField(default=list, help_text='Professional areas to focus on')),
                ('competencies_to_develop', models.JSONField(default=list, help_text='Competencies to develop or enhance')),
                ('total_hours_planned', models.DecimalField(decimal_places=2, help_text='Total CPD hours planned for the year', max_digits=5)),
                ('active_cpd_hours_planned', models.DecimalField(decimal_places=2, help_text='Active CPD hours planned (minimum 50% of total)', max_digits=5)),
                ('peer_consultation_hours_planned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Peer consultation hours planned', max_digits=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('total_hours_completed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('active_cpd_hours_completed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('peer_consultation_hours_completed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cpd_plans', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpd_plans', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpd_plans', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'CPD Plan',
                'verbose_name_plural': 'CPD Plans',
                'ordering': ['-year', '-created_at'],
                'indexes': [models.Index(fields=['user', 'year'], name='cpd_portfol_user_id_933ec0_idx'), models.Index(fields=['status'], name='cpd_portfol_status_bdf96c_idx')],
                'unique_together': {('user', 'year')},
            },
        ),
    ]
